src/components/MewSuperButton/MewSuperButton.vue
=> Add mew-super-button mobile layout

src/assets/images/icons/stake.svg, src/components/MewIcon/MewIcon.vue, stories/MewIcon/MewIcon.stories.js
=> Add stake icon

src/components/MewNotification/MewNotification.vue
=> ui: updated mew notifications

package.json, src/components/MewNotification/MewNotification.vue
- changed 'activated' to 'expanded'
- added margin to the right of the to object container 
- added padding to the indicator 
- use eth img placeholder if there is no data
=> update mew notification

package.json, src/assets/styles/basics/_input.scss, src/components/MewSelect/MewSelect.vue, stories/MewSelect/MewSelect.stories.js
https://app.asana.com/0/1163629870679883/1200555217954525
=> Add border to tokens

src/assets/images/icons/stakewise-green.svg, src/assets/images/icons/stakewise-purple.svg, src/assets/images/icons/stakewise-red.svg, src/assets/images/icons/stakewise.svg, src/components/MewIcon/MewIcon.vue
mew-icon: add stakewise icon image
=> mew-icon: add stakewise

src/components/MewPopup/MewPopup.vue
https://user-images.githubusercontent.com/9893774/160731249-e8ce77ef-e412-4f54-93fc-a8f1114905a7.mp4
=> fix: mew-popup close button z-index value to locate the button on top

src/components/MewStepper/MewStepper.vue, stories/MewStepper/MewStepper.stories.js
=> fix: add compact option for mobile ui

src/components/MewTabs/MewTabs.vue, src/plugins/vuetify.js, stories/MewTabs/MewTabs.stories.js
=> fix: update mobile tab header buttons

src/components/MewSelect/MewSelect.vue
=> fix: remove circle from mew-select

src/components/MewAddressSelect/MewAddressSelect.vue
fix bug that doesn't close dropdown when outside window is clicked
https://user-images.githubusercontent.com/9893774/178184259-674b8bcd-9c41-4221-9eb3-10b95a5b3a16.mp4
=> fix: dropdown menu not closing bug

package.json, src/components/MewAddressSelect/MewAddressSelect.vue, stories/MewAddressSelect/MewAddressSelect.stories.js
https://app.asana.com/0/1163629870679883/1202570223232821
=> add hint prop to mew address seleect

src/components/MewSelect/MewSelect.vue
Places the exact match on the top of the list
=> devop: Put exact match on top of list of search

src/components/MewSelect/MewSelect.vue, stories/MewSelect/MewSelect.stories.js
fix unwanted capitalize style from mew selec
t
=> fix: fix unwanted capitalize style from mew select

src/components/MewSelect/MewSelect.vue
fix icon width resizing issue
https://myetherwallet.atlassian.net/jira/software/projects/MWD/boards/8?assignee=62bb6562fa171a27239d206f&selectedIssue=MWD-90
=> fix: mew-select icon width resizing issue

src/components/MewTable/MewTable.vue
fix mew-table token icon resizing issue
=> fix: mew-table token icon resizing issue

src/components/MewButton/MewButton.vue
=> devop: adjust button latter spacing

src/components/MewSelect/MewSelect.vue
remove mew select search border radius
=> fix: remove select search border radius

CHANGELOG.md, package-lock.json, package.json, src/components/MewAddressSelect/MewAddressSelect.vue, stories/MewAddressSelect/MewAddressSelect.stories.js
=> Devop: address select display save icon option

package-lock.json, package.json, src/components/MewAddressSelect/MewAddressSelect.vue
Revert changes made to blockie hash to fix wrong identicons
=> fix: wrong identicons on resolved address

src/components/MewAddressSelect/MewAddressSelect.vue, src/components/MewBlockie/MewBlockie.vue, src/components/MewNotification/MewNotification.vue
=> fix: swap notification arrow alignment

package-lock.json, src/components/MewAddressSelect/MewAddressSelect.vue, src/components/MewBlockie/MewBlockie.vue, src/components/MewLightTable/MewLightTable.vue, src/components/MewTooltip/MewTooltip.vue, stories/MewLightTable/MewLightTable.mdx, stories/MewLightTable/MewLightTable.stories.js
https://myetherwallet.atlassian.net/jira/software/projects/MWD/boards/8?selectedIssue=MWD-321&text=table
Add new MewLightTable component.
=> devop: add new mew light table

src/assets/styles/vuetifyTheme.js, src/components/MewInput/MewInput.vue
https://myetherwallet.atlassian.net/jira/software/projects/DES/boards/9?selectedIssue=DES-40&text=colors
https://www.figma.com/file/X7fvmomTnbDCi1ZJwP9ZaS/%F0%9F%8E%A8-UI-Library?node-id=1267%3A11383
=> devop: update colors

CHANGELOG.md, package-lock.json, package.json, src/components/MewButton/MewButton.vue, src/components/MewIconButton/MewIconButton.vue, src/components/MewModule/MewModule.vue, src/components/MewNotification/MewNotification.vue, src/components/MewOverlay/MewOverlay.vue, src/components/MewPopup/MewPopup.vue, src/components/MewSearch/MewSearch.vue, src/components/MewSelect/MewSelect.vue
=> fix: dark theme notification slot color issues
